default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: input.txt
    -   id: end-of-file-fixer
        exclude: input.txt
    -   id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  -   id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.194"
  hooks:
    - id: ruff
      # match statement not supported in ruff
      exclude: days/07/part2.py|days/18/part2.py|days/24/day_24.py/days/19/part1.py|^days/19/
